language: python
sudo: false
python:
  - "3.6"

before_install:
  - pip install --upgrade pip

install:
  - pip install awscli

script:
  - export AWS_ACCESS_KEY_ID
  - export AWS_SECRET_ACCESS_KEY
  - export AWS_DEFAULT_REGION
  - chmod +x .travis_asg.sh
  - ./.travis_asg.sh
